/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bonsaiapp;

import java.awt.Color;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author skyla
 */
public class MainWindow extends javax.swing.JFrame {

    private HashMap<String, User> users;
    private ArrayList<Transaction> transactions;
    private DataFactory dataFactory = new DataFactory();
    private User userLogged;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        StartConfigs();

        //change data type to string
        // Get the data from the DataFactory classs
        users = dataFactory.users;
        transactions = dataFactory.transactions;

        String data = displayData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void StartConfigs() {
        MainWindow.setVisible(false);
        longWindow_label_wornglogin.setVisible(false);
        RegistrationWindow.setVisible(false);
        MainWindow_Panel_Owe.setVisible(false);
        MainWindow_Panel_Request.setVisible(false);
        LoginWindow.setVisible(true);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginWindow = new javax.swing.JPanel();
        loginWindow_label_username = new javax.swing.JLabel();
        loginWindow_textField_password = new javax.swing.JTextField();
        loginWindow_label_password = new javax.swing.JLabel();
        loginWindow_textField_username = new javax.swing.JTextField();
        loginWindow_button_enter = new javax.swing.JButton();
        loginWindow_Button_newUser = new javax.swing.JButton();
        LoginWindow_label_logo = new javax.swing.JLabel();
        longWindow_label_wornglogin = new javax.swing.JLabel();
        loginWindow_label_username1 = new javax.swing.JLabel();
        MainWindow = new javax.swing.JPanel();
        MainWindow_ToggleB_Dashboard = new javax.swing.JToggleButton();
        MainWindow_ToggleB_Dues = new javax.swing.JToggleButton();
        MainWindow_ToggleB_History = new javax.swing.JToggleButton();
        MainWindow_Panel_Holder = new javax.swing.JPanel();
        MainWindow_Panel_Dashboard = new javax.swing.JPanel();
        Main_Dashboard_Text_ExpectedProfits1 = new javax.swing.JLabel();
        Main_Dashboard_Text_Money1 = new javax.swing.JLabel();
        Main_Dashboard_Table_Data3 = new javax.swing.JScrollPane();
        MainDashboard_Table = new javax.swing.JTable();
        Main_Dashboard_Button_Request1 = new javax.swing.JButton();
        Main_Dashboard_Button_Owe1 = new javax.swing.JButton();
        MainWindow_Panel_Request = new javax.swing.JPanel();
        MainWindow_label_Reason1 = new javax.swing.JLabel();
        MainWindow_textField_username1 = new javax.swing.JTextField();
        MainWindow_textField_amount1 = new javax.swing.JTextField();
        MainWindow_textField_textareascroll1 = new javax.swing.JScrollPane();
        MainWindow_textArea_reason1 = new javax.swing.JTextArea();
        MainWindow_button_submitRequest = new javax.swing.JButton();
        MainWindow_button_cancel1 = new javax.swing.JButton();
        MainWindow_label_owe1 = new javax.swing.JLabel();
        MainWindow_label_username1 = new javax.swing.JLabel();
        MainWindow_label_amount1 = new javax.swing.JLabel();
        MainWindow_Panel_Owe = new javax.swing.JPanel();
        MainWindow_label_Reason = new javax.swing.JLabel();
        MainWindow_textField_username = new javax.swing.JTextField();
        MainWindow_textField_amount = new javax.swing.JTextField();
        MainWindow_textField_textareascroll = new javax.swing.JScrollPane();
        MainWindow_textArea_reason = new javax.swing.JTextArea();
        MainWindow_button_submitOwe = new javax.swing.JButton();
        MainWindow_button_cancel = new javax.swing.JButton();
        MainWindow_label_owe = new javax.swing.JLabel();
        MainWindow_label_username = new javax.swing.JLabel();
        MainWindow_label_amount = new javax.swing.JLabel();
        MainWindow_Panel_Dues = new javax.swing.JPanel();
        Main_Dashboard_Table_Data1 = new javax.swing.JScrollPane();
        DuePanel_Table = new javax.swing.JTable();
        DueWindow_Label_yourdues = new javax.swing.JLabel();
        DueWindow_Label_dues = new javax.swing.JLabel();
        MainWindow_Panel_History = new javax.swing.JPanel();
        Main_Dashboard_Table_Data2 = new javax.swing.JScrollPane();
        HistoryLog_Table = new javax.swing.JTable();
        HistoryLog_label_HL = new javax.swing.JLabel();
        UserInfo = new javax.swing.JPanel();
        Main_UserInfo_Text_Username = new javax.swing.JLabel();
        Main_UserInfo_Button_LogOut = new javax.swing.JButton();
        RegistrationWindow = new javax.swing.JPanel();
        RegWindow_label_newuser = new javax.swing.JLabel();
        RegWindow_button_register = new javax.swing.JButton();
        RegWindow_textfield_username = new javax.swing.JTextField();
        RegWindow_textfield_password = new javax.swing.JTextField();
        RegWindow_textfiled_realname = new javax.swing.JTextField();
        RegWindow_label_realname = new javax.swing.JLabel();
        RegWindow_label_password = new javax.swing.JLabel();
        RegWindow_label_username = new javax.swing.JLabel();
        RegWindow_button_back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("loginWindow");
        setMaximumSize(new java.awt.Dimension(540, 850));
        setPreferredSize(new java.awt.Dimension(540, 850));

        LoginWindow.setBackground(new java.awt.Color(102, 102, 102));
        LoginWindow.setDoubleBuffered(false);

        loginWindow_label_username.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        loginWindow_label_username.setForeground(new java.awt.Color(242, 242, 242));
        loginWindow_label_username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginWindow_label_username.setText("Because Money Dont Grow on Trees");

        loginWindow_textField_password.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        loginWindow_label_password.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        loginWindow_label_password.setForeground(new java.awt.Color(242, 242, 242));
        loginWindow_label_password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginWindow_label_password.setText("Password");

        loginWindow_textField_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        loginWindow_button_enter.setBackground(new java.awt.Color(0, 153, 0));
        loginWindow_button_enter.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginWindow_button_enter.setForeground(new java.awt.Color(242, 242, 242));
        loginWindow_button_enter.setText("Enter");
        loginWindow_button_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginWindow_button_enterActionPerformed(evt);
            }
        });

        loginWindow_Button_newUser.setBackground(new java.awt.Color(0, 153, 0));
        loginWindow_Button_newUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginWindow_Button_newUser.setForeground(new java.awt.Color(242, 242, 242));
        loginWindow_Button_newUser.setText("New User?");
        loginWindow_Button_newUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginWindow_Button_newUserMouseClicked(evt);
            }
        });
        loginWindow_Button_newUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginWindow_Button_newUserActionPerformed(evt);
            }
        });

        LoginWindow_label_logo.setBackground(new java.awt.Color(0, 204, 51));
        LoginWindow_label_logo.setFont(new java.awt.Font("Perpetua", 3, 70)); // NOI18N
        LoginWindow_label_logo.setForeground(new java.awt.Color(0, 204, 51));
        LoginWindow_label_logo.setText("Bonsai");

        longWindow_label_wornglogin.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        longWindow_label_wornglogin.setForeground(new java.awt.Color(255, 0, 0));
        longWindow_label_wornglogin.setText("Wrong password/username, try again");

        loginWindow_label_username1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        loginWindow_label_username1.setForeground(new java.awt.Color(242, 242, 242));
        loginWindow_label_username1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginWindow_label_username1.setText("Username");

        javax.swing.GroupLayout LoginWindowLayout = new javax.swing.GroupLayout(LoginWindow);
        LoginWindow.setLayout(LoginWindowLayout);
        LoginWindowLayout.setHorizontalGroup(
            LoginWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginWindowLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(LoginWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginWindowLayout.createSequentialGroup()
                        .addComponent(loginWindow_textField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginWindowLayout.createSequentialGroup()
                        .addComponent(loginWindow_label_password, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginWindowLayout.createSequentialGroup()
                        .addGroup(LoginWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(loginWindow_label_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(loginWindow_textField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))))
            .addGroup(LoginWindowLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(LoginWindow_label_logo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginWindowLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loginWindow_label_username1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
            .addGroup(LoginWindowLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(LoginWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(longWindow_label_wornglogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(LoginWindowLayout.createSequentialGroup()
                        .addComponent(loginWindow_button_enter, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loginWindow_Button_newUser, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61))
        );
        LoginWindowLayout.setVerticalGroup(
            LoginWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginWindowLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(LoginWindow_label_logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginWindow_label_username)
                .addGap(127, 127, 127)
                .addComponent(loginWindow_label_username1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginWindow_textField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginWindow_label_password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginWindow_textField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(LoginWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginWindow_button_enter, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginWindow_Button_newUser, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(longWindow_label_wornglogin, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        MainWindow.setBackground(new java.awt.Color(102, 102, 102));
        MainWindow.setEnabled(false);

        MainWindow_ToggleB_Dashboard.setBackground(new java.awt.Color(0, 153, 51));
        MainWindow_ToggleB_Dashboard.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        MainWindow_ToggleB_Dashboard.setForeground(new java.awt.Color(242, 242, 242));
        MainWindow_ToggleB_Dashboard.setText("Dashboard");
        MainWindow_ToggleB_Dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainWindow_ToggleB_DashboardActionPerformed(evt);
            }
        });

        MainWindow_ToggleB_Dues.setBackground(new java.awt.Color(0, 153, 51));
        MainWindow_ToggleB_Dues.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        MainWindow_ToggleB_Dues.setForeground(new java.awt.Color(242, 242, 242));
        MainWindow_ToggleB_Dues.setText("Dues");
        MainWindow_ToggleB_Dues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainWindow_ToggleB_DuesActionPerformed(evt);
            }
        });

        MainWindow_ToggleB_History.setBackground(new java.awt.Color(0, 153, 51));
        MainWindow_ToggleB_History.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        MainWindow_ToggleB_History.setForeground(new java.awt.Color(242, 242, 242));
        MainWindow_ToggleB_History.setText("History");
        MainWindow_ToggleB_History.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainWindow_ToggleB_HistoryActionPerformed(evt);
            }
        });

        MainWindow_Panel_Holder.setBackground(new java.awt.Color(204, 204, 204));

        MainWindow_Panel_Dashboard.setBackground(new java.awt.Color(102, 102, 102));

        Main_Dashboard_Text_ExpectedProfits1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        Main_Dashboard_Text_ExpectedProfits1.setForeground(new java.awt.Color(242, 242, 242));
        Main_Dashboard_Text_ExpectedProfits1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Main_Dashboard_Text_ExpectedProfits1.setText("Expected Profits:");
        Main_Dashboard_Text_ExpectedProfits1.setToolTipText("");

        Main_Dashboard_Text_Money1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 2, 48)); // NOI18N
        Main_Dashboard_Text_Money1.setForeground(new java.awt.Color(0, 153, 0));
        Main_Dashboard_Text_Money1.setText("Money NUM HERE");

        MainDashboard_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name + Reason", "Type", "Amount", "Done?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        MainDashboard_Table.setEnabled(false);
        Main_Dashboard_Table_Data3.setViewportView(MainDashboard_Table);

        Main_Dashboard_Button_Request1.setBackground(new java.awt.Color(0, 153, 0));
        Main_Dashboard_Button_Request1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Main_Dashboard_Button_Request1.setForeground(new java.awt.Color(242, 242, 242));
        Main_Dashboard_Button_Request1.setText("Request");
        Main_Dashboard_Button_Request1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_Dashboard_Button_Request1ActionPerformed(evt);
            }
        });

        Main_Dashboard_Button_Owe1.setBackground(new java.awt.Color(0, 153, 0));
        Main_Dashboard_Button_Owe1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Main_Dashboard_Button_Owe1.setForeground(new java.awt.Color(242, 242, 242));
        Main_Dashboard_Button_Owe1.setText("Owe");
        Main_Dashboard_Button_Owe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_Dashboard_Button_Owe1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainWindow_Panel_DashboardLayout = new javax.swing.GroupLayout(MainWindow_Panel_Dashboard);
        MainWindow_Panel_Dashboard.setLayout(MainWindow_Panel_DashboardLayout);
        MainWindow_Panel_DashboardLayout.setHorizontalGroup(
            MainWindow_Panel_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainWindow_Panel_DashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Main_Dashboard_Table_Data3, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainWindow_Panel_DashboardLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(Main_Dashboard_Button_Owe1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Main_Dashboard_Button_Request1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainWindow_Panel_DashboardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MainWindow_Panel_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainWindow_Panel_DashboardLayout.createSequentialGroup()
                        .addComponent(Main_Dashboard_Text_Money1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainWindow_Panel_DashboardLayout.createSequentialGroup()
                        .addComponent(Main_Dashboard_Text_ExpectedProfits1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140))))
        );
        MainWindow_Panel_DashboardLayout.setVerticalGroup(
            MainWindow_Panel_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainWindow_Panel_DashboardLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Main_Dashboard_Text_ExpectedProfits1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Main_Dashboard_Text_Money1)
                .addGap(46, 46, 46)
                .addGroup(MainWindow_Panel_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Main_Dashboard_Button_Owe1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Main_Dashboard_Button_Request1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Main_Dashboard_Table_Data3, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        MainWindow_Panel_Request.setBackground(new java.awt.Color(102, 102, 102));

        MainWindow_label_Reason1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        MainWindow_label_Reason1.setForeground(new java.awt.Color(242, 242, 242));
        MainWindow_label_Reason1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainWindow_label_Reason1.setText("Reason");
        MainWindow_label_Reason1.setToolTipText("");

        MainWindow_textArea_reason1.setColumns(20);
        MainWindow_textArea_reason1.setRows(5);
        MainWindow_textField_textareascroll1.setViewportView(MainWindow_textArea_reason1);

        MainWindow_button_submitRequest.setBackground(new java.awt.Color(0, 204, 0));
        MainWindow_button_submitRequest.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        MainWindow_button_submitRequest.setForeground(new java.awt.Color(242, 242, 242));
        MainWindow_button_submitRequest.setText("Submit");
        MainWindow_button_submitRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainWindow_button_submitRequestActionPerformed(evt);
            }
        });

        MainWindow_button_cancel1.setBackground(new java.awt.Color(153, 0, 51));
        MainWindow_button_cancel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MainWindow_button_cancel1.setForeground(new java.awt.Color(242, 242, 242));
        MainWindow_button_cancel1.setText("Cancel");
        MainWindow_button_cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainWindow_button_cancel1ActionPerformed(evt);
            }
        });

        MainWindow_label_owe1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        MainWindow_label_owe1.setForeground(new java.awt.Color(0, 204, 0));
        MainWindow_label_owe1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainWindow_label_owe1.setText("Request");
        MainWindow_label_owe1.setToolTipText("");

        MainWindow_label_username1.setFont(new java.awt.Font("Myanmar Text", 1, 24)); // NOI18N
        MainWindow_label_username1.setForeground(new java.awt.Color(242, 242, 242));
        MainWindow_label_username1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainWindow_label_username1.setText("Username(From)");
        MainWindow_label_username1.setToolTipText("");

        MainWindow_label_amount1.setFont(new java.awt.Font("Myanmar Text", 1, 24)); // NOI18N
        MainWindow_label_amount1.setForeground(new java.awt.Color(242, 242, 242));
        MainWindow_label_amount1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainWindow_label_amount1.setText("Amount (Ex: 12.43)");
        MainWindow_label_amount1.setToolTipText("");

        javax.swing.GroupLayout MainWindow_Panel_RequestLayout = new javax.swing.GroupLayout(MainWindow_Panel_Request);
        MainWindow_Panel_Request.setLayout(MainWindow_Panel_RequestLayout);
        MainWindow_Panel_RequestLayout.setHorizontalGroup(
            MainWindow_Panel_RequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainWindow_Panel_RequestLayout.createSequentialGroup()
                .addGroup(MainWindow_Panel_RequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainWindow_Panel_RequestLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(MainWindow_Panel_RequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MainWindow_textField_amount1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                            .addComponent(MainWindow_textField_username1)))
                    .addGroup(MainWindow_Panel_RequestLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(MainWindow_label_username1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainWindow_Panel_RequestLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(MainWindow_button_submitRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainWindow_Panel_RequestLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(MainWindow_button_cancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainWindow_Panel_RequestLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(MainWindow_label_Reason1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainWindow_Panel_RequestLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(MainWindow_label_amount1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainWindow_Panel_RequestLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(MainWindow_label_owe1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainWindow_Panel_RequestLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(MainWindow_textField_textareascroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        MainWindow_Panel_RequestLayout.setVerticalGroup(
            MainWindow_Panel_RequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainWindow_Panel_RequestLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(MainWindow_label_owe1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(MainWindow_label_username1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainWindow_textField_username1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(MainWindow_label_amount1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainWindow_textField_amount1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(MainWindow_label_Reason1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainWindow_textField_textareascroll1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(MainWindow_button_submitRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MainWindow_button_cancel1)
                .addGap(47, 47, 47))
        );

        MainWindow_Panel_Owe.setBackground(new java.awt.Color(102, 102, 102));

        MainWindow_label_Reason.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        MainWindow_label_Reason.setForeground(new java.awt.Color(242, 242, 242));
        MainWindow_label_Reason.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainWindow_label_Reason.setText("Reason");
        MainWindow_label_Reason.setToolTipText("");

        MainWindow_textArea_reason.setColumns(20);
        MainWindow_textArea_reason.setRows(5);
        MainWindow_textField_textareascroll.setViewportView(MainWindow_textArea_reason);

        MainWindow_button_submitOwe.setBackground(new java.awt.Color(0, 204, 0));
        MainWindow_button_submitOwe.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        MainWindow_button_submitOwe.setForeground(new java.awt.Color(242, 242, 242));
        MainWindow_button_submitOwe.setText("Submit");
        MainWindow_button_submitOwe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainWindow_button_submitOweActionPerformed(evt);
            }
        });

        MainWindow_button_cancel.setBackground(new java.awt.Color(153, 0, 51));
        MainWindow_button_cancel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MainWindow_button_cancel.setForeground(new java.awt.Color(242, 242, 242));
        MainWindow_button_cancel.setText("Cancel");
        MainWindow_button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainWindow_button_cancelActionPerformed(evt);
            }
        });

        MainWindow_label_owe.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        MainWindow_label_owe.setForeground(new java.awt.Color(0, 204, 0));
        MainWindow_label_owe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainWindow_label_owe.setText("Owe");
        MainWindow_label_owe.setToolTipText("");

        MainWindow_label_username.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        MainWindow_label_username.setForeground(new java.awt.Color(242, 242, 242));
        MainWindow_label_username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainWindow_label_username.setText("Username(To)");
        MainWindow_label_username.setToolTipText("");

        MainWindow_label_amount.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        MainWindow_label_amount.setForeground(new java.awt.Color(242, 242, 242));
        MainWindow_label_amount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainWindow_label_amount.setText("Amount (Ex: 12.43)");
        MainWindow_label_amount.setToolTipText("");

        javax.swing.GroupLayout MainWindow_Panel_OweLayout = new javax.swing.GroupLayout(MainWindow_Panel_Owe);
        MainWindow_Panel_Owe.setLayout(MainWindow_Panel_OweLayout);
        MainWindow_Panel_OweLayout.setHorizontalGroup(
            MainWindow_Panel_OweLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainWindow_Panel_OweLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(MainWindow_Panel_OweLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainWindow_Panel_OweLayout.createSequentialGroup()
                        .addComponent(MainWindow_label_owe, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainWindow_Panel_OweLayout.createSequentialGroup()
                        .addComponent(MainWindow_label_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))))
            .addGroup(MainWindow_Panel_OweLayout.createSequentialGroup()
                .addGroup(MainWindow_Panel_OweLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainWindow_Panel_OweLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(MainWindow_Panel_OweLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MainWindow_textField_textareascroll, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                            .addComponent(MainWindow_textField_amount)
                            .addComponent(MainWindow_textField_username)))
                    .addGroup(MainWindow_Panel_OweLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(MainWindow_label_username, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainWindow_Panel_OweLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(MainWindow_label_Reason, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainWindow_Panel_OweLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(MainWindow_button_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainWindow_Panel_OweLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(MainWindow_button_submitOwe, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        MainWindow_Panel_OweLayout.setVerticalGroup(
            MainWindow_Panel_OweLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainWindow_Panel_OweLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(MainWindow_label_owe, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(MainWindow_label_username, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainWindow_textField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(MainWindow_label_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainWindow_textField_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(MainWindow_label_Reason, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainWindow_textField_textareascroll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(MainWindow_button_submitOwe, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MainWindow_button_cancel)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        MainWindow_Panel_Dues.setBackground(new java.awt.Color(102, 102, 102));

        Main_Dashboard_Table_Data1.setViewportView(DuePanel_Table);
        if (DuePanel_Table.getColumnModel().getColumnCount() > 0) {
            DuePanel_Table.getColumnModel().getColumn(0).setHeaderValue("Name + Reason");
            DuePanel_Table.getColumnModel().getColumn(1).setHeaderValue("Amount");
        }

        DueWindow_Label_yourdues.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        DueWindow_Label_yourdues.setForeground(new java.awt.Color(242, 242, 242));
        DueWindow_Label_yourdues.setText("Your Dues:");

        DueWindow_Label_dues.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        DueWindow_Label_dues.setForeground(new java.awt.Color(255, 51, 51));
        DueWindow_Label_dues.setText("Number is here");

        javax.swing.GroupLayout MainWindow_Panel_DuesLayout = new javax.swing.GroupLayout(MainWindow_Panel_Dues);
        MainWindow_Panel_Dues.setLayout(MainWindow_Panel_DuesLayout);
        MainWindow_Panel_DuesLayout.setHorizontalGroup(
            MainWindow_Panel_DuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainWindow_Panel_DuesLayout.createSequentialGroup()
                .addGroup(MainWindow_Panel_DuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainWindow_Panel_DuesLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(DueWindow_Label_yourdues))
                    .addGroup(MainWindow_Panel_DuesLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(Main_Dashboard_Table_Data1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainWindow_Panel_DuesLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(DueWindow_Label_dues)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        MainWindow_Panel_DuesLayout.setVerticalGroup(
            MainWindow_Panel_DuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainWindow_Panel_DuesLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(DueWindow_Label_yourdues)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DueWindow_Label_dues)
                .addGap(47, 47, 47)
                .addComponent(Main_Dashboard_Table_Data1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        MainWindow_Panel_History.setBackground(new java.awt.Color(102, 102, 102));
        MainWindow_Panel_History.setMaximumSize(new java.awt.Dimension(518, 823));

        HistoryLog_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name + Reason", "Type", "Amount"
            }
        ));
        Main_Dashboard_Table_Data2.setViewportView(HistoryLog_Table);

        HistoryLog_label_HL.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        HistoryLog_label_HL.setForeground(new java.awt.Color(0, 204, 0));
        HistoryLog_label_HL.setText("History Log");

        javax.swing.GroupLayout MainWindow_Panel_HistoryLayout = new javax.swing.GroupLayout(MainWindow_Panel_History);
        MainWindow_Panel_History.setLayout(MainWindow_Panel_HistoryLayout);
        MainWindow_Panel_HistoryLayout.setHorizontalGroup(
            MainWindow_Panel_HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainWindow_Panel_HistoryLayout.createSequentialGroup()
                .addGroup(MainWindow_Panel_HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainWindow_Panel_HistoryLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(Main_Dashboard_Table_Data2, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainWindow_Panel_HistoryLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(HistoryLog_label_HL)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        MainWindow_Panel_HistoryLayout.setVerticalGroup(
            MainWindow_Panel_HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainWindow_Panel_HistoryLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(HistoryLog_label_HL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Main_Dashboard_Table_Data2, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        UserInfo.setBackground(new java.awt.Color(204, 204, 204));

        Main_UserInfo_Text_Username.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Main_UserInfo_Text_Username.setText("Name HERE");

        javax.swing.GroupLayout UserInfoLayout = new javax.swing.GroupLayout(UserInfo);
        UserInfo.setLayout(UserInfoLayout);
        UserInfoLayout.setHorizontalGroup(
            UserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserInfoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Main_UserInfo_Text_Username)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UserInfoLayout.setVerticalGroup(
            UserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Main_UserInfo_Text_Username)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        Main_UserInfo_Button_LogOut.setText("LOG OUT X");
        Main_UserInfo_Button_LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_UserInfo_Button_LogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainWindow_Panel_HolderLayout = new javax.swing.GroupLayout(MainWindow_Panel_Holder);
        MainWindow_Panel_Holder.setLayout(MainWindow_Panel_HolderLayout);
        MainWindow_Panel_HolderLayout.setHorizontalGroup(
            MainWindow_Panel_HolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainWindow_Panel_HolderLayout.createSequentialGroup()
                .addComponent(UserInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Main_UserInfo_Button_LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(MainWindow_Panel_History, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(MainWindow_Panel_HolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MainWindow_Panel_Dues, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(MainWindow_Panel_HolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MainWindow_Panel_Owe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(MainWindow_Panel_HolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MainWindow_Panel_HolderLayout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(MainWindow_Panel_Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(6, 6, 6)))
            .addGroup(MainWindow_Panel_HolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MainWindow_Panel_HolderLayout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addComponent(MainWindow_Panel_Request, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(6, 6, 6)))
        );
        MainWindow_Panel_HolderLayout.setVerticalGroup(
            MainWindow_Panel_HolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainWindow_Panel_HolderLayout.createSequentialGroup()
                .addGroup(MainWindow_Panel_HolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Main_UserInfo_Button_LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainWindow_Panel_History, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(MainWindow_Panel_HolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainWindow_Panel_HolderLayout.createSequentialGroup()
                    .addGap(0, 61, Short.MAX_VALUE)
                    .addComponent(MainWindow_Panel_Dues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(MainWindow_Panel_HolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainWindow_Panel_HolderLayout.createSequentialGroup()
                    .addGap(0, 58, Short.MAX_VALUE)
                    .addComponent(MainWindow_Panel_Owe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(MainWindow_Panel_HolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MainWindow_Panel_HolderLayout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(MainWindow_Panel_Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(MainWindow_Panel_HolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MainWindow_Panel_HolderLayout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addComponent(MainWindow_Panel_Request, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(22, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout MainWindowLayout = new javax.swing.GroupLayout(MainWindow);
        MainWindow.setLayout(MainWindowLayout);
        MainWindowLayout.setHorizontalGroup(
            MainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainWindow_Panel_Holder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MainWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainWindow_ToggleB_Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainWindow_ToggleB_Dues, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainWindow_ToggleB_History, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        MainWindowLayout.setVerticalGroup(
            MainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainWindowLayout.createSequentialGroup()
                .addComponent(MainWindow_Panel_Holder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MainWindow_ToggleB_Dues, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MainWindow_ToggleB_Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MainWindow_ToggleB_History, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        RegistrationWindow.setBackground(new java.awt.Color(102, 102, 102));
        RegistrationWindow.setEnabled(false);

        RegWindow_label_newuser.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        RegWindow_label_newuser.setForeground(new java.awt.Color(0, 204, 0));
        RegWindow_label_newuser.setText("New User Registration");

        RegWindow_button_register.setBackground(new java.awt.Color(0, 153, 0));
        RegWindow_button_register.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        RegWindow_button_register.setForeground(new java.awt.Color(242, 242, 242));
        RegWindow_button_register.setText("Register");
        RegWindow_button_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegWindow_button_registerActionPerformed(evt);
            }
        });

        RegWindow_label_realname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RegWindow_label_realname.setForeground(new java.awt.Color(242, 242, 242));
        RegWindow_label_realname.setText("Your Real Name");

        RegWindow_label_password.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RegWindow_label_password.setForeground(new java.awt.Color(242, 242, 242));
        RegWindow_label_password.setText("Your Password");

        RegWindow_label_username.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RegWindow_label_username.setForeground(new java.awt.Color(242, 242, 242));
        RegWindow_label_username.setText("Your Username");

        RegWindow_button_back.setBackground(new java.awt.Color(255, 0, 51));
        RegWindow_button_back.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RegWindow_button_back.setForeground(new java.awt.Color(242, 242, 242));
        RegWindow_button_back.setText("<-Back");
        RegWindow_button_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegWindow_button_backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout RegistrationWindowLayout = new javax.swing.GroupLayout(RegistrationWindow);
        RegistrationWindow.setLayout(RegistrationWindowLayout);
        RegistrationWindowLayout.setHorizontalGroup(
            RegistrationWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrationWindowLayout.createSequentialGroup()
                .addGroup(RegistrationWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(RegistrationWindowLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(RegistrationWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegWindow_textfield_username, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegWindow_textfield_password, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegWindow_textfiled_realname, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(RegistrationWindowLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(RegWindow_label_password))
                    .addGroup(RegistrationWindowLayout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(RegWindow_label_username))
                    .addGroup(RegistrationWindowLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(RegWindow_button_register, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegistrationWindowLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(RegWindow_button_back)
                        .addGroup(RegistrationWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegistrationWindowLayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(RegWindow_label_realname))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrationWindowLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(RegWindow_label_newuser)))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        RegistrationWindowLayout.setVerticalGroup(
            RegistrationWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrationWindowLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(RegistrationWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegWindow_button_back, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RegWindow_label_newuser, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(RegWindow_label_realname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegWindow_textfiled_realname, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(RegWindow_label_username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegWindow_textfield_username, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(RegWindow_label_password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RegWindow_textfield_password, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96)
                .addComponent(RegWindow_button_register, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LoginWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(RegistrationWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 18, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(MainWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LoginWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(RegistrationWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(MainWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        LoginWindow.getAccessibleContext().setAccessibleDescription("");

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegWindow_button_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RegWindow_button_backMouseClicked
        RegistrationWindow.setVisible(false);
        MainWindow_Panel_Owe.setVisible(false);
        MainWindow_Panel_Request.setVisible(false);
        LoginWindow.setVisible(true);
        MainWindow.setVisible(false);
    }//GEN-LAST:event_RegWindow_button_backMouseClicked

    private void MainWindow_ToggleB_DashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainWindow_ToggleB_DashboardActionPerformed
        MainWindow_Panel_Holder.setVisible(true);
        MainWindow_Panel_Owe.setVisible(true);
        MainWindow_Panel_Owe.setVisible(false);
        MainWindow_Panel_Request.setVisible(false);
        MainWindow_Panel_Dues.setVisible(false);
        MainWindow_Panel_History.setVisible(false);
        MainWindow_ToggleB_History.setSelected(false);
        MainWindow_ToggleB_Dashboard.setSelected(true);
        MainWindow_ToggleB_Dues.setSelected(false);
    }//GEN-LAST:event_MainWindow_ToggleB_DashboardActionPerformed

    private void Main_UserInfo_Button_LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_UserInfo_Button_LogOutActionPerformed
        //toggle buttons need to be untoggles when anothe button is clicked
        MainWindow.setVisible(false);
        MainWindow_Panel_Owe.setVisible(false);
        MainWindow_Panel_Request.setVisible(false);
        LoginWindow.setVisible(true);
        RegistrationWindow.setVisible(false);
    }//GEN-LAST:event_Main_UserInfo_Button_LogOutActionPerformed

    private void MainWindow_ToggleB_DuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainWindow_ToggleB_DuesActionPerformed
        //toggle buttons need to be untoggles when anothe button is clicked
        MainWindow_Panel_Holder.setVisible(true);
        MainWindow_Panel_Owe.setVisible(false);
        MainWindow_Panel_Dues.setVisible(true);
        MainWindow_Panel_History.setVisible(false);
        MainWindow_ToggleB_History.setSelected(false);
        MainWindow_Panel_Owe.setVisible(false);
        MainWindow_Panel_Request.setVisible(false);
        MainWindow_ToggleB_Dashboard.setSelected(false);
        MainWindow_ToggleB_Dues.setSelected(true);
    }//GEN-LAST:event_MainWindow_ToggleB_DuesActionPerformed

    private void MainWindow_ToggleB_HistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainWindow_ToggleB_HistoryActionPerformed
        //toggle buttons need to be untoggles when anothe button is clicked
        MainWindow_Panel_Holder.setVisible(true);
        MainWindow_Panel_Owe.setVisible(false);
        MainWindow_Panel_Dues.setVisible(false);
        MainWindow_Panel_History.setVisible(true);
        MainWindow_Panel_Owe.setVisible(false);
        MainWindow_Panel_Request.setVisible(false);
        MainWindow_ToggleB_History.setSelected(true);
        MainWindow_ToggleB_Dashboard.setSelected(false);
        MainWindow_ToggleB_Dues.setSelected(false);
    }//GEN-LAST:event_MainWindow_ToggleB_HistoryActionPerformed

    private void loginWindow_Button_newUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginWindow_Button_newUserMouseClicked
        RegistrationWindow.setVisible(true);
        LoginWindow.setVisible(false);
        MainWindow_Panel_Owe.setVisible(false);
        MainWindow_Panel_Request.setVisible(false);
        MainWindow.setVisible(false);
    }//GEN-LAST:event_loginWindow_Button_newUserMouseClicked

    private void loginWindow_button_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginWindow_button_enterActionPerformed
        // Get the username and password from the login form
        String username = loginWindow_textField_username.getText();
        String password = loginWindow_textField_password.getText();

        // Get the username list
        List<String> usernames = new ArrayList<>();
        for (User user : users.values()) {
            usernames.add(user.getUserName());
        }

        // Check if the username is in the list
        if (!usernames.contains(username)) {
            // Invalid username
            JOptionPane.showMessageDialog(null, "Invalid username");
            return;
        }

        // Check if the password is correct
        User user = users.get(username);

        if (password == null || !password.equals(user.getPassword())) {
            // Invalid password
            JOptionPane.showMessageDialog(null, "Invalid password");
            return;
        }

        //assign a user that is logged to the global varibale userLogged to use it in different methods
        userLogged = user;
        DebtSimplification ds = new DebtSimplification(userLogged, transactions);

        //update all tables
        buildDashboardTable();
        buildDuesTable();
        buildHistorytable();
        UsernamePUT();

        MainWindow.setVisible(true);
        MainWindow_Panel_Holder.setVisible(true);
        MainWindow_Panel_Owe.setVisible(true);
        MainWindow_Panel_Dues.setVisible(false);
        MainWindow_Panel_History.setVisible(false);
        LoginWindow.setVisible(false);
        MainWindow_Panel_Owe.setVisible(false);
        MainWindow_Panel_Request.setVisible(false);
        RegistrationWindow.setVisible(false);
        MainWindow_ToggleB_Dashboard.setVisible(true);
        MainWindow_ToggleB_Dues.setVisible(true);
        MainWindow_ToggleB_History.setVisible(true);

    }//GEN-LAST:event_loginWindow_button_enterActionPerformed
    private void loginWindow_Button_newUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginWindow_Button_newUserActionPerformed
        // this code will move user to the regestration window
    }//GEN-LAST:event_loginWindow_Button_newUserActionPerformed

    private void RegWindow_button_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegWindow_button_registerActionPerformed
        // Get the real name, username, and password from the registration form
        String realName = RegWindow_textfiled_realname.getText();
        String username = RegWindow_textfield_username.getText();
        String password = RegWindow_textfield_password.getText();

        // Check if all the data is entered
        if (realName.isEmpty() || username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter all the required data");
            return;
        }

        // Check if the username already exists
        //DataFactory dataFactory = new DataFactory();
        User user = users.get(username);
        if (user != null) {
            // Username already exists
            JOptionPane.showMessageDialog(null, "Username already exists");
            return;
        }

        // Create a new user + assign to global variable
        user = new User(username, realName, password);
        users.put(username, user);
        userLogged = user;

        //update all the tables
        buildDashboardTable();
        buildDuesTable();
        buildHistorytable();
        UsernamePUT();

        MainWindow.setVisible(true);
        MainWindow_Panel_Holder.setVisible(true);
        MainWindow_Panel_Owe.setVisible(true);
        MainWindow_Panel_Dues.setVisible(false);
        MainWindow_Panel_History.setVisible(false);
        LoginWindow.setVisible(false);
        MainWindow_Panel_Owe.setVisible(false);
        MainWindow_Panel_Request.setVisible(false);
        RegistrationWindow.setVisible(false);
        MainWindow_ToggleB_Dashboard.setVisible(true);
        MainWindow_ToggleB_Dues.setVisible(true);
        MainWindow_ToggleB_History.setVisible(true);
    }//GEN-LAST:event_RegWindow_button_registerActionPerformed

    private void Main_Dashboard_Button_Owe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_Dashboard_Button_Owe1ActionPerformed
        MainWindow_Panel_Dashboard.setVisible(false);
        MainWindow_Panel_Owe.setVisible(true);

        MainWindow_ToggleB_Dashboard.setVisible(false);
        MainWindow_ToggleB_Dues.setVisible(false);
        MainWindow_ToggleB_History.setVisible(false);
    }//GEN-LAST:event_Main_Dashboard_Button_Owe1ActionPerformed

    private void Main_Dashboard_Button_Request1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_Dashboard_Button_Request1ActionPerformed
        MainWindow_Panel_Dashboard.setVisible(false);
        MainWindow_Panel_Request.setVisible(true);

        MainWindow_ToggleB_Dashboard.setVisible(false);
        MainWindow_ToggleB_Dues.setVisible(false);
        MainWindow_ToggleB_History.setVisible(false);
    }//GEN-LAST:event_Main_Dashboard_Button_Request1ActionPerformed

    private void MainWindow_button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainWindow_button_cancelActionPerformed
        MainWindow_Panel_Dashboard.setVisible(true);
        MainWindow_Panel_Owe.setVisible(false);

        MainWindow_ToggleB_Dashboard.setVisible(true);
        MainWindow_ToggleB_Dues.setVisible(true);
        MainWindow_ToggleB_History.setVisible(true);
    }//GEN-LAST:event_MainWindow_button_cancelActionPerformed

    private void MainWindow_button_cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainWindow_button_cancel1ActionPerformed
        MainWindow_Panel_Dashboard.setVisible(true);
        MainWindow_Panel_Request.setVisible(false);

        MainWindow_ToggleB_Dashboard.setVisible(true);
        MainWindow_ToggleB_Dues.setVisible(true);
        MainWindow_ToggleB_History.setVisible(true);
    }//GEN-LAST:event_MainWindow_button_cancel1ActionPerformed

    private void MainWindow_button_submitOweActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainWindow_button_submitOweActionPerformed
        //1. this code will collect all the data from the text boxes and create a transaction object adding to the global transaction list
        //1.5 checks id name is correct + checks if number is provided(not word or letter)
        //2. UPdate all of the teable (Or the ones that will add new Owe)
        //2.5 create a local time stamp for this object
        //3. switch to the dashboard

        String name = MainWindow_textField_username.getText();
        String amount = MainWindow_textField_amount.getText();
        String reason = MainWindow_textArea_reason.getText();

        String disname = userLogged.getUserName();
        
        // Get the username list
        List<String> usernames = new ArrayList<>();
        for (User u : users.values()) {
            usernames.add(u.getUserName());
        }

        
        // Check if the username is in the list
        if (!usernames.contains(name)) {
            // Invalid username
            JOptionPane.showMessageDialog(null, "Invalid username");
            return;
        }

        if (!amount.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "Amount must be a number.");
            return;
        }

        // 1. Create a new Transaction object
        Transaction transaction = new Transaction(disname, "owe", Double.parseDouble(amount), name, reason, false);

        // 1. Add the transaction to the "transactions" global variable in MainWindow
        transactions.add(transaction);
        
        DebtSimplification ds = new DebtSimplification(userLogged, transactions);

        //refresh the tables
        buildDashboardTable();
        buildDuesTable();
        buildHistorytable();
        UsernamePUT();
        
        MainWindow_Panel_Dashboard.setVisible(true);
        MainWindow_Panel_Owe.setVisible(false);

        MainWindow_ToggleB_Dashboard.setVisible(true);
        MainWindow_ToggleB_Dues.setVisible(true);
        MainWindow_ToggleB_History.setVisible(true);
    }//GEN-LAST:event_MainWindow_button_submitOweActionPerformed

    private void MainWindow_button_submitRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainWindow_button_submitRequestActionPerformed
        //1. this code will collect all the data from the text boxes and create a transaction object adding to the global transaction list
        //1.5 checks id name is correct + checks if number is provided(not word or letter)
        //2. UPdate all of the teable (Or the ones that will add new Request)
        //2.5 create a local time stamp for this object
        //3. switch to the dashboard

        String name = MainWindow_textField_username1.getText();
        String amount = MainWindow_textField_amount1.getText();
        String reason = MainWindow_textArea_reason1.getText();

        String disname = userLogged.getUserName();

        // Get the username list
        List<String> usernames = new ArrayList<>();
        for (User u : users.values()) {
            usernames.add(u.getUserName());
        }

        // Check if the username is in the list
        if (!usernames.contains(name)) {
            // Invalid username
            JOptionPane.showMessageDialog(null, "Invalid username");
            return;
        }

        if (!amount.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "Amount must be a number.");
            return;
        }

        // 1. Create a new Transaction object
        Transaction transaction = new Transaction(disname, "request", Double.parseDouble(amount), name, reason, false);

        // 1. Add the transaction to the "transactions" global variable in MainWindow
        transactions.add(transaction);
        

        //need to refresh
        DebtSimplification ds = new DebtSimplification(userLogged, transactions);
        
        buildDashboardTable();
        buildDuesTable();
        buildHistorytable();
        UsernamePUT();
        
        MainWindow_Panel_Dashboard.setVisible(true);
        MainWindow_Panel_Request.setVisible(false);

        MainWindow_ToggleB_Dashboard.setVisible(true);
        MainWindow_ToggleB_Dues.setVisible(true);
        MainWindow_ToggleB_History.setVisible(true);

    }//GEN-LAST:event_MainWindow_button_submitRequestActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //idk whats that
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    //this method gets model of the user, by taking the user + transaction of the user based on the key(username)
    public BonsaiManagerModel getModel() {
        return new BonsaiManagerModel(users, transactions); //its actually arraylist
    }

    //this was a test method that is displaying data from the text files.
    //making sure that our data extraction logic is wokring correctly
    private String displayData() {
        StringBuilder sb = new StringBuilder();

        //Accessing the data and printing them out in the assigned text filed for both user and transaction
        sb.append("USERS:\n");
        for (User user : users.values()) {
            sb.append("* ").append(user.getUserName()).append(" - ").append(user.getDisplayName()).append(" - ").append(user.getPassword()).append("\n");
        }

        sb.append("\nTRANSACTIONS:\n");
        for (Transaction transaction : transactions) {
            sb.append("* ").append(transaction.getDate()).append(" - ").append(transaction.getUserNameFrom()).append(" - ").append(transaction.getReason()).append("\n");
        }

        return sb.toString();
    }

    public void buildDashboardTable() {
        //this class will build a table for the dashboard by taking all the tranaction data and inputing it into the table. 
        //showign total balance with + and -
        //Need to run again as soon as we create new due or request

        ArrayList<Transaction> UserTransaction = userLogged.getUserTransactions();

        Object[][] data = null;
        String[] headers = {"Name + Reason", "Type", "Amount", "Done?"};
        
        //this logic will take the transaction of the specific user and then take all neccessary info
        //and input them into the table + following the table heading format
        if (UserTransaction != null) {
            data = new Object[UserTransaction.size()][4];

            int row = 0;

            for (Transaction t : UserTransaction) {
                String displayName = users.get(t.getUserNameFrom()).getDisplayName();
                data[row][0] = displayName + ", " + t.getReason();
                data[row][1] = t.getTransactionType();
                data[row][2] = t.getAmount();
                data[row][3] = t.isDone();
                row++;
            }
        }
        DefaultTableModel dfm = (DefaultTableModel) MainDashboard_Table.getModel();
        dfm.setDataVector(data, headers);
    }

    public void buildDuesTable() {
        //takes only due data and showign it up with the total amount due
        //called when new due is created, it is going to update the due chart only

        ArrayList<Transaction> DueTransaction = userLogged.getDueTransactions();

        //is there anything? no? then its none.
        if (DueTransaction == null) {
            return;
        }

        Object[][] data = new Object[DueTransaction.size()][2];
        String[] headers = {"Name + Reason", "Amount"};

        int row = 0;

        //this logic will take the transaction of the specific user and then take all neccessary info
        //and input them into the table + following the table heading format
        //Only dues are taken
        for (Transaction t : DueTransaction) {
            String displayName = users.get(t.getUserNameFrom()).getDisplayName();
            data[row][0] = displayName + ", " + t.getReason();
            data[row][1] = t.getAmount();
            row++;
        }

        DefaultTableModel dfm = (DefaultTableModel) DuePanel_Table.getModel();
        dfm.setDataVector(data, headers);
    }

    public void buildHistorytable() {
        //takes all of the tranasction data and retireves all info to display as reason, from, and to whom
        //updates only history table
        //called every time there is new due or request is added

        ArrayList<Transaction> DoneTransaction = userLogged.getDoneTransactions();

        if (DoneTransaction == null) {
            return;
        }

        Object[][] data = new Object[DoneTransaction.size()][3];
        String[] headers = {"Name + Reason", "Type", "Amount"};

        int row = 0;

        //this logic will take the transaction of the specific user and then take all neccessary info
        //and input them into the table + following the table heading format
        //Only DONE are taken
        for (Transaction t : DoneTransaction) {
            String displayName = users.get(t.getUserNameFrom()).getDisplayName();
            data[row][0] = displayName + ", " + t.getReason();
            data[row][1] = t.getTransactionType();
            data[row][2] = t.getAmount();
            row++;
        }

        DefaultTableModel dfm = (DefaultTableModel) HistoryLog_Table.getModel();
        dfm.setDataVector(data, headers);
    }

    //this is unique method that will switch all the texts in the MainWindow with
    //the information that was provided by user(login or registration)
    //it will replace all "TEXT HERE" everywhere with approprtiate information
    //also this method calculates the total and due balance for the tables
    //also this method recolor numbers based on the balance (negative = red, positive = green, 0 = gray)
    public void UsernamePUT() {
        String na = userLogged.getUserName();
        Main_UserInfo_Text_Username.setText(na);

        ArrayList<Transaction> UserTransaction = userLogged.getUserTransactions();
        ArrayList<Transaction> DueTransaction = userLogged.getDueTransactions();

        int row1 = 0;
        double totaldue = 0;

        int row2 = 0;
        double totaluser = 0;

        if (userLogged.getUserTransactions() != null) {
            for (Transaction t : DueTransaction) {
                double mon = t.getAmount();
                totaldue -= mon;
                row1++;
            }

            for (Transaction t : UserTransaction) {
                double mon2 = t.getAmount();
                String type = t.getTransactionType();
                if (type.equals("owe") && 
                    t.getUserNameFrom().equals(userLogged.getUserName()) &&
                    !t.isDone()) {
                        totaluser -= mon2;
                    }
                else if (type.equals("owe") &&
                    t.getUserNameTo().equals(userLogged.getUserName()) &&
                    !t.isDone()) {
                        totaluser += mon2;
                    }
                
                else if (type.equals("request") &&
                        t.getUserNameFrom().equals(userLogged.getUserName()) &&
                        !t.isDone()) {
                            totaluser += mon2;
                    }
                else {
                    if (!t.isDone()) {
                        totaluser -= mon2;
                    }
                }

                row2++;
            }
        }

        if (totaluser < 0) {
            Main_Dashboard_Text_Money1.setForeground(Color.red);
        } else if (totaluser == 0) {
            Main_Dashboard_Text_Money1.setForeground(Color.gray);
        } else {
            Main_Dashboard_Text_Money1.setForeground(Color.green);
        }
        DueWindow_Label_dues.setText("$" + totaldue + "");
        Main_Dashboard_Text_Money1.setText("$" + totaluser + "");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DuePanel_Table;
    private javax.swing.JLabel DueWindow_Label_dues;
    private javax.swing.JLabel DueWindow_Label_yourdues;
    private javax.swing.JTable HistoryLog_Table;
    private javax.swing.JLabel HistoryLog_label_HL;
    private javax.swing.JPanel LoginWindow;
    private javax.swing.JLabel LoginWindow_label_logo;
    private javax.swing.JTable MainDashboard_Table;
    private javax.swing.JPanel MainWindow;
    private javax.swing.JPanel MainWindow_Panel_Dashboard;
    private javax.swing.JPanel MainWindow_Panel_Dues;
    private javax.swing.JPanel MainWindow_Panel_History;
    private javax.swing.JPanel MainWindow_Panel_Holder;
    private javax.swing.JPanel MainWindow_Panel_Owe;
    private javax.swing.JPanel MainWindow_Panel_Request;
    private javax.swing.JToggleButton MainWindow_ToggleB_Dashboard;
    private javax.swing.JToggleButton MainWindow_ToggleB_Dues;
    private javax.swing.JToggleButton MainWindow_ToggleB_History;
    private javax.swing.JButton MainWindow_button_cancel;
    private javax.swing.JButton MainWindow_button_cancel1;
    private javax.swing.JButton MainWindow_button_submitOwe;
    private javax.swing.JButton MainWindow_button_submitRequest;
    private javax.swing.JLabel MainWindow_label_Reason;
    private javax.swing.JLabel MainWindow_label_Reason1;
    private javax.swing.JLabel MainWindow_label_amount;
    private javax.swing.JLabel MainWindow_label_amount1;
    private javax.swing.JLabel MainWindow_label_owe;
    private javax.swing.JLabel MainWindow_label_owe1;
    private javax.swing.JLabel MainWindow_label_username;
    private javax.swing.JLabel MainWindow_label_username1;
    private javax.swing.JTextArea MainWindow_textArea_reason;
    private javax.swing.JTextArea MainWindow_textArea_reason1;
    private javax.swing.JTextField MainWindow_textField_amount;
    private javax.swing.JTextField MainWindow_textField_amount1;
    private javax.swing.JScrollPane MainWindow_textField_textareascroll;
    private javax.swing.JScrollPane MainWindow_textField_textareascroll1;
    private javax.swing.JTextField MainWindow_textField_username;
    private javax.swing.JTextField MainWindow_textField_username1;
    private javax.swing.JButton Main_Dashboard_Button_Owe1;
    private javax.swing.JButton Main_Dashboard_Button_Request1;
    private javax.swing.JScrollPane Main_Dashboard_Table_Data1;
    private javax.swing.JScrollPane Main_Dashboard_Table_Data2;
    private javax.swing.JScrollPane Main_Dashboard_Table_Data3;
    private javax.swing.JLabel Main_Dashboard_Text_ExpectedProfits1;
    private javax.swing.JLabel Main_Dashboard_Text_Money1;
    private javax.swing.JButton Main_UserInfo_Button_LogOut;
    private javax.swing.JLabel Main_UserInfo_Text_Username;
    private javax.swing.JButton RegWindow_button_back;
    private javax.swing.JButton RegWindow_button_register;
    private javax.swing.JLabel RegWindow_label_newuser;
    private javax.swing.JLabel RegWindow_label_password;
    private javax.swing.JLabel RegWindow_label_realname;
    private javax.swing.JLabel RegWindow_label_username;
    private javax.swing.JTextField RegWindow_textfield_password;
    private javax.swing.JTextField RegWindow_textfield_username;
    private javax.swing.JTextField RegWindow_textfiled_realname;
    private javax.swing.JPanel RegistrationWindow;
    private javax.swing.JPanel UserInfo;
    private javax.swing.JButton loginWindow_Button_newUser;
    private javax.swing.JButton loginWindow_button_enter;
    private javax.swing.JLabel loginWindow_label_password;
    private javax.swing.JLabel loginWindow_label_username;
    private javax.swing.JLabel loginWindow_label_username1;
    private javax.swing.JTextField loginWindow_textField_password;
    private javax.swing.JTextField loginWindow_textField_username;
    private javax.swing.JLabel longWindow_label_wornglogin;
    // End of variables declaration//GEN-END:variables
}
