/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bonsaiapp;

import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Scanner;
import java.util.TreeSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author skyla
 */
public class MainWindow extends javax.swing.JFrame {
    
    private HashMap<String, User> users;
    private ArrayList<Transaction> transactions;
    private DataFactory dataFactory;
     

    /**
     * Creates new form MainWindow
     */     
     public MainWindow() {       
        initComponents();
        StartConfigs(); 
        
        //DataFactory df = new DataFactory();
        
        //change data type to string
        // Get the data from the DataFactory class
        DataFactory dataFactory = new DataFactory();
        String data = displayData(dataFactory);

        // Display the data in the jTextPane1 text field
        jTextArea1.setText(data);
        
        //BonsaiManagerModel data = readModel();
        //user = data.user();
        //transaction = data.transaction();
        
        //BonsaiManagerModel data = df.getModel();
        //users = data.user;
        //transactions = data.transaction;
        
        //NOT WORKING YET, CANNOT GET THE USER YET
        //User x = users.get("alejdiaz");
        
        //System.out.println(x); //test if see if its work
        //System.out.println(transactions);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void StartConfigs(){
        MainWindow.setVisible(false);
        longWindow_label_wornglogin.setVisible(false);
        RegistrationWindow.setVisible(false);
        LoginWindow.setVisible(true);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoginWindow = new javax.swing.JPanel();
        loginWindow_label_username = new javax.swing.JLabel();
        loginWindow_textField_password = new javax.swing.JTextField();
        loginWindow_label_password = new javax.swing.JLabel();
        loginWindow_textField_username = new javax.swing.JTextField();
        loginWindow_button_enter = new javax.swing.JButton();
        loginWindow_Button_newUser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        longWindow_label_wornglogin = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        MainWindow = new javax.swing.JPanel();
        MainWindow_ToggleB_Dashboard = new javax.swing.JToggleButton();
        MainWindow_ToggleB_Dues = new javax.swing.JToggleButton();
        MainWindow_ToggleB_History = new javax.swing.JToggleButton();
        MainWindow_Panel_Holder = new javax.swing.JPanel();
        MainWindow_Panel_Dashboard = new javax.swing.JPanel();
        Main_Dashboard_Text_ExpectedProfits = new javax.swing.JLabel();
        Main_Dashboard_Text_Money = new javax.swing.JLabel();
        Main_Dashboard_Table_Data = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Main_Dashboard_Button_Request = new javax.swing.JButton();
        Main_Dashboard_Button_Owe = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        MainWindow_Panel_Dues = new javax.swing.JPanel();
        Main_Dashboard_Table_Data1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        MainWindow_Panel_History = new javax.swing.JPanel();
        Main_Dashboard_Table_Data2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        UserInfo = new javax.swing.JPanel();
        Main_UserInfo_Text_Username = new javax.swing.JLabel();
        Main_UserInfo_Button_LogOut = new javax.swing.JButton();
        RegistrationWindow = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("loginWindow");
        setMaximumSize(new java.awt.Dimension(540, 850));
        setPreferredSize(new java.awt.Dimension(540, 850));

        LoginWindow.setBackground(new java.awt.Color(102, 102, 102));
        LoginWindow.setDoubleBuffered(false);

        loginWindow_label_username.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        loginWindow_label_username.setForeground(new java.awt.Color(242, 242, 242));
        loginWindow_label_username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginWindow_label_username.setText("Username");

        loginWindow_textField_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginWindow_textField_passwordActionPerformed(evt);
            }
        });

        loginWindow_label_password.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        loginWindow_label_password.setForeground(new java.awt.Color(242, 242, 242));
        loginWindow_label_password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginWindow_label_password.setText("Password");

        loginWindow_textField_username.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        loginWindow_button_enter.setText("Enter");
        loginWindow_button_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginWindow_button_enterActionPerformed(evt);
            }
        });

        loginWindow_Button_newUser.setText("New User?");
        loginWindow_Button_newUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginWindow_Button_newUserMouseClicked(evt);
            }
        });
        loginWindow_Button_newUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginWindow_Button_newUserActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 204, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 51));
        jLabel1.setText("Bonsai");

        longWindow_label_wornglogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        longWindow_label_wornglogin.setForeground(new java.awt.Color(255, 0, 0));
        longWindow_label_wornglogin.setText("Wrong password/username, try again");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout LoginWindowLayout = new javax.swing.GroupLayout(LoginWindow);
        LoginWindow.setLayout(LoginWindowLayout);
        LoginWindowLayout.setHorizontalGroup(
            LoginWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginWindowLayout.createSequentialGroup()
                .addGroup(LoginWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginWindowLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(loginWindow_label_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(loginWindow_label_username, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(LoginWindowLayout.createSequentialGroup()
                        .addGroup(LoginWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LoginWindowLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(longWindow_label_wornglogin))
                            .addGroup(LoginWindowLayout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(jLabel1))
                            .addGroup(LoginWindowLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(loginWindow_textField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(LoginWindowLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(loginWindow_textField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(LoginWindowLayout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(loginWindow_button_enter, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(loginWindow_Button_newUser, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(LoginWindowLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LoginWindowLayout.setVerticalGroup(
            LoginWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginWindowLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginWindow_label_username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginWindow_textField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loginWindow_label_password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginWindow_textField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(LoginWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginWindow_button_enter, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginWindow_Button_newUser, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addComponent(longWindow_label_wornglogin, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        MainWindow.setBackground(new java.awt.Color(102, 102, 102));
        MainWindow.setEnabled(false);

        MainWindow_ToggleB_Dashboard.setBackground(new java.awt.Color(0, 153, 51));
        MainWindow_ToggleB_Dashboard.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MainWindow_ToggleB_Dashboard.setForeground(new java.awt.Color(242, 242, 242));
        MainWindow_ToggleB_Dashboard.setText("Dashboard");
        MainWindow_ToggleB_Dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainWindow_ToggleB_DashboardActionPerformed(evt);
            }
        });

        MainWindow_ToggleB_Dues.setBackground(new java.awt.Color(0, 153, 51));
        MainWindow_ToggleB_Dues.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MainWindow_ToggleB_Dues.setForeground(new java.awt.Color(242, 242, 242));
        MainWindow_ToggleB_Dues.setText("Dues");
        MainWindow_ToggleB_Dues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainWindow_ToggleB_DuesActionPerformed(evt);
            }
        });

        MainWindow_ToggleB_History.setBackground(new java.awt.Color(0, 153, 51));
        MainWindow_ToggleB_History.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MainWindow_ToggleB_History.setForeground(new java.awt.Color(242, 242, 242));
        MainWindow_ToggleB_History.setText("History");
        MainWindow_ToggleB_History.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainWindow_ToggleB_HistoryActionPerformed(evt);
            }
        });

        MainWindow_Panel_Holder.setBackground(new java.awt.Color(204, 204, 204));

        MainWindow_Panel_Dashboard.setBackground(new java.awt.Color(102, 102, 102));

        Main_Dashboard_Text_ExpectedProfits.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        Main_Dashboard_Text_ExpectedProfits.setForeground(new java.awt.Color(242, 242, 242));
        Main_Dashboard_Text_ExpectedProfits.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Main_Dashboard_Text_ExpectedProfits.setText("Expected Profits:");
        Main_Dashboard_Text_ExpectedProfits.setToolTipText("");

        Main_Dashboard_Text_Money.setFont(new java.awt.Font("Segoe UI Semibold", 2, 36)); // NOI18N
        Main_Dashboard_Text_Money.setForeground(new java.awt.Color(255, 51, 51));
        Main_Dashboard_Text_Money.setText("Money NUM HERE");

        Main_Dashboard_Table_Data.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Name + Reason");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Amount");
        }

        Main_Dashboard_Button_Request.setText("Request");

        Main_Dashboard_Button_Owe.setText("Owe");

        jButton1.setText("Show the Chart");

        javax.swing.GroupLayout MainWindow_Panel_DashboardLayout = new javax.swing.GroupLayout(MainWindow_Panel_Dashboard);
        MainWindow_Panel_Dashboard.setLayout(MainWindow_Panel_DashboardLayout);
        MainWindow_Panel_DashboardLayout.setHorizontalGroup(
            MainWindow_Panel_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainWindow_Panel_DashboardLayout.createSequentialGroup()
                .addGroup(MainWindow_Panel_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainWindow_Panel_DashboardLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(Main_Dashboard_Text_ExpectedProfits, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 132, Short.MAX_VALUE))
                    .addGroup(MainWindow_Panel_DashboardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Main_Dashboard_Table_Data)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainWindow_Panel_DashboardLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(Main_Dashboard_Button_Owe, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Main_Dashboard_Button_Request, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainWindow_Panel_DashboardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(MainWindow_Panel_DashboardLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(Main_Dashboard_Text_Money)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainWindow_Panel_DashboardLayout.setVerticalGroup(
            MainWindow_Panel_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainWindow_Panel_DashboardLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(Main_Dashboard_Text_ExpectedProfits, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Main_Dashboard_Text_Money)
                .addGap(17, 17, 17)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Main_Dashboard_Table_Data, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(MainWindow_Panel_DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Main_Dashboard_Button_Request, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Main_Dashboard_Button_Owe, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        MainWindow_Panel_Dues.setBackground(new java.awt.Color(102, 102, 102));

        Main_Dashboard_Table_Data1.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setHeaderValue("Name + Reason");
            jTable2.getColumnModel().getColumn(1).setHeaderValue("Amount");
        }

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(242, 242, 242));
        jLabel7.setText("Your Dues:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setText("Number is here");

        jButton4.setText("Show the Chart");

        javax.swing.GroupLayout MainWindow_Panel_DuesLayout = new javax.swing.GroupLayout(MainWindow_Panel_Dues);
        MainWindow_Panel_Dues.setLayout(MainWindow_Panel_DuesLayout);
        MainWindow_Panel_DuesLayout.setHorizontalGroup(
            MainWindow_Panel_DuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainWindow_Panel_DuesLayout.createSequentialGroup()
                .addGroup(MainWindow_Panel_DuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainWindow_Panel_DuesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Main_Dashboard_Table_Data1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE))
                    .addGroup(MainWindow_Panel_DuesLayout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainWindow_Panel_DuesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(MainWindow_Panel_DuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainWindow_Panel_DuesLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(166, 166, 166))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainWindow_Panel_DuesLayout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addContainerGap())))
        );
        MainWindow_Panel_DuesLayout.setVerticalGroup(
            MainWindow_Panel_DuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainWindow_Panel_DuesLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Main_Dashboard_Table_Data1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        MainWindow_Panel_History.setBackground(new java.awt.Color(102, 102, 102));
        MainWindow_Panel_History.setMaximumSize(new java.awt.Dimension(518, 823));

        Main_Dashboard_Table_Data2.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setHeaderValue("Name + Reason");
            jTable3.getColumnModel().getColumn(1).setHeaderValue("Amount");
        }

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(242, 242, 242));
        jLabel9.setText("steam");

        jButton5.setText("Show the Chart");

        javax.swing.GroupLayout MainWindow_Panel_HistoryLayout = new javax.swing.GroupLayout(MainWindow_Panel_History);
        MainWindow_Panel_History.setLayout(MainWindow_Panel_HistoryLayout);
        MainWindow_Panel_HistoryLayout.setHorizontalGroup(
            MainWindow_Panel_HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainWindow_Panel_HistoryLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(MainWindow_Panel_HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainWindow_Panel_HistoryLayout.createSequentialGroup()
                        .addComponent(Main_Dashboard_Table_Data2, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(MainWindow_Panel_HistoryLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addContainerGap())
        );
        MainWindow_Panel_HistoryLayout.setVerticalGroup(
            MainWindow_Panel_HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainWindow_Panel_HistoryLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MainWindow_Panel_HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Main_Dashboard_Table_Data2, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );

        UserInfo.setBackground(new java.awt.Color(204, 204, 204));

        Main_UserInfo_Text_Username.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Main_UserInfo_Text_Username.setText("Name HERE");

        Main_UserInfo_Button_LogOut.setText("LOG OUT X");
        Main_UserInfo_Button_LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Main_UserInfo_Button_LogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UserInfoLayout = new javax.swing.GroupLayout(UserInfo);
        UserInfo.setLayout(UserInfoLayout);
        UserInfoLayout.setHorizontalGroup(
            UserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserInfoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Main_UserInfo_Text_Username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Main_UserInfo_Button_LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        UserInfoLayout.setVerticalGroup(
            UserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserInfoLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(Main_UserInfo_Text_Username)
                .addContainerGap())
            .addGroup(UserInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Main_UserInfo_Button_LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MainWindow_Panel_HolderLayout = new javax.swing.GroupLayout(MainWindow_Panel_Holder);
        MainWindow_Panel_Holder.setLayout(MainWindow_Panel_HolderLayout);
        MainWindow_Panel_HolderLayout.setHorizontalGroup(
            MainWindow_Panel_HolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainWindow_Panel_HolderLayout.createSequentialGroup()
                .addComponent(UserInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(102, 102, 102))
            .addComponent(MainWindow_Panel_History, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MainWindow_Panel_HolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MainWindow_Panel_Dues, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(MainWindow_Panel_HolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(MainWindow_Panel_Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainWindow_Panel_HolderLayout.setVerticalGroup(
            MainWindow_Panel_HolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainWindow_Panel_HolderLayout.createSequentialGroup()
                .addComponent(UserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MainWindow_Panel_History, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(MainWindow_Panel_HolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainWindow_Panel_HolderLayout.createSequentialGroup()
                    .addGap(0, 65, Short.MAX_VALUE)
                    .addComponent(MainWindow_Panel_Dues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(MainWindow_Panel_HolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainWindow_Panel_HolderLayout.createSequentialGroup()
                    .addGap(0, 149, Short.MAX_VALUE)
                    .addComponent(MainWindow_Panel_Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout MainWindowLayout = new javax.swing.GroupLayout(MainWindow);
        MainWindow.setLayout(MainWindowLayout);
        MainWindowLayout.setHorizontalGroup(
            MainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainWindow_Panel_Holder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MainWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainWindow_ToggleB_Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainWindow_ToggleB_Dues, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainWindow_ToggleB_History, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        MainWindowLayout.setVerticalGroup(
            MainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainWindowLayout.createSequentialGroup()
                .addComponent(MainWindow_Panel_Holder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MainWindow_ToggleB_Dues, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MainWindow_ToggleB_Dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MainWindow_ToggleB_History, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        RegistrationWindow.setBackground(new java.awt.Color(102, 102, 102));
        RegistrationWindow.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("New User Registration");

        jButton2.setText("Register");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Your Real Name");

        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("Your Password");

        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText("Your Username");

        jScrollPane1.setViewportView(jTextPane1);

        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("Error Console");

        jButton3.setText("<-Back");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout RegistrationWindowLayout = new javax.swing.GroupLayout(RegistrationWindow);
        RegistrationWindow.setLayout(RegistrationWindowLayout);
        RegistrationWindowLayout.setHorizontalGroup(
            RegistrationWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrationWindowLayout.createSequentialGroup()
                .addGroup(RegistrationWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrationWindowLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegistrationWindowLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton3)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel2))
                    .addGroup(RegistrationWindowLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(RegistrationWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(RegistrationWindowLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel3))
                    .addGroup(RegistrationWindowLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel4))
                    .addGroup(RegistrationWindowLayout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel5))
                    .addGroup(RegistrationWindowLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegistrationWindowLayout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel6)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        RegistrationWindowLayout.setVerticalGroup(
            RegistrationWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrationWindowLayout.createSequentialGroup()
                .addGroup(RegistrationWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrationWindowLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RegistrationWindowLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addGap(38, 38, 38)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LoginWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(RegistrationWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(MainWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(7, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LoginWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(RegistrationWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(MainWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(45, Short.MAX_VALUE)))
        );

        LoginWindow.getAccessibleContext().setAccessibleDescription("");

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
       RegistrationWindow.setVisible(false);
       LoginWindow.setVisible(true);
       MainWindow.setVisible(false);
    }//GEN-LAST:event_jButton3MouseClicked

    private void MainWindow_ToggleB_DashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainWindow_ToggleB_DashboardActionPerformed
        MainWindow_Panel_Holder.setVisible(true);
        MainWindow_Panel_Dashboard.setVisible(true);
        MainWindow_Panel_Dues.setVisible(false);
        MainWindow_Panel_History.setVisible(false);
        MainWindow_ToggleB_History.setSelected(false);
        MainWindow_ToggleB_Dashboard.setSelected(true);
        MainWindow_ToggleB_Dues.setSelected(false);
    }//GEN-LAST:event_MainWindow_ToggleB_DashboardActionPerformed

    private void Main_UserInfo_Button_LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Main_UserInfo_Button_LogOutActionPerformed
        //toggle buttons need to be untoggles when anothe button is clicked
        MainWindow.setVisible(false);
        LoginWindow.setVisible(true);
        RegistrationWindow.setVisible(false);
    }//GEN-LAST:event_Main_UserInfo_Button_LogOutActionPerformed

    private void MainWindow_ToggleB_DuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainWindow_ToggleB_DuesActionPerformed
        //toggle buttons need to be untoggles when anothe button is clicked
        MainWindow_Panel_Holder.setVisible(true);
        MainWindow_Panel_Dashboard.setVisible(false);
        MainWindow_Panel_Dues.setVisible(true);
        MainWindow_Panel_History.setVisible(false);
        MainWindow_ToggleB_History.setSelected(false);
        MainWindow_ToggleB_Dashboard.setSelected(false);
        MainWindow_ToggleB_Dues.setSelected(true);
    }//GEN-LAST:event_MainWindow_ToggleB_DuesActionPerformed

    private void MainWindow_ToggleB_HistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MainWindow_ToggleB_HistoryActionPerformed
        //toggle buttons need to be untoggles when anothe button is clicked
        MainWindow_Panel_Holder.setVisible(true);
        MainWindow_Panel_Dashboard.setVisible(false);
        MainWindow_Panel_Dues.setVisible(false);
        MainWindow_Panel_History.setVisible(true);
        MainWindow_ToggleB_History.setSelected(true);
        MainWindow_ToggleB_Dashboard.setSelected(false);
        MainWindow_ToggleB_Dues.setSelected(false);
    }//GEN-LAST:event_MainWindow_ToggleB_HistoryActionPerformed

    private void loginWindow_Button_newUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginWindow_Button_newUserMouseClicked
        RegistrationWindow.setVisible(true);
        LoginWindow.setVisible(false);
        MainWindow.setVisible(false);
    }//GEN-LAST:event_loginWindow_Button_newUserMouseClicked

    private void loginWindow_button_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginWindow_button_enterActionPerformed
    // CHECK IF LOGIN INFO IS WORKING

    // Get the username and password from the login form
    String username = loginWindow_textField_username.getText();
    String password = loginWindow_textField_password.getText();

    // Create an instance of the DataFactory class
    DataFactory dataFactory = new DataFactory();

    // Check if the username and password are valid
    User user = dataFactory.users.get(password);
    if (user == null || !user.getPassword().equals(password)) {
        // Invalid username or password
        JOptionPane.showMessageDialog(null, "Invalid username or password");
        return;
    }

    // Login the user
    MainWindow.setVisible(true);
    MainWindow_Panel_Holder.setVisible(true);
    MainWindow_Panel_Dashboard.setVisible(true);
    MainWindow_Panel_Dues.setVisible(false);
    MainWindow_Panel_History.setVisible(false);
    LoginWindow.setVisible(false);
    RegistrationWindow.setVisible(false);
    }//GEN-LAST:event_loginWindow_button_enterActionPerformed

    private void loginWindow_textField_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginWindow_textField_passwordActionPerformed
        //text
    }//GEN-LAST:event_loginWindow_textField_passwordActionPerformed

    private void loginWindow_Button_newUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginWindow_Button_newUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginWindow_Button_newUserActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Get the real name, username, and password from the registration form
        String realName = jTextField5.getText();
        String username = jTextField3.getText();
        String password = jTextField4.getText();

        // Create an instance of the DataFactory class
        DataFactory dataFactory = new DataFactory();

        // Check if the username already exists
        User user = dataFactory.users.get(username);
        if (user != null) {
            // Username already exists
            JOptionPane.showMessageDialog(null, "Username already exists");
            return;
        }

        // Create a new user
        user = new User(realName, username, password);
        dataFactory.users.put(username, user);

        // Write the user data to the UserCSV.txt file
        try {
            FileWriter fw = new FileWriter("UserCSV.txt");
            for (User u : dataFactory.users.values()) {
                fw.write(u.toString() + "\n");
            }
            fw.close();
        } catch (IOException e) {
            e.printStackTrace();
        }

        // Login the user
        MainWindow.setVisible(true);
        MainWindow_Panel_Holder.setVisible(true);
        MainWindow_Panel_Dashboard.setVisible(true);
        MainWindow_Panel_Dues.setVisible(false);
        MainWindow_Panel_History.setVisible(false);
        LoginWindow.setVisible(false);
        RegistrationWindow.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    
    
    public BonsaiManagerModel getModel(){      
        return new BonsaiManagerModel(users, transactions); //its actually arraylist
    }
    
    private String displayData(DataFactory dataFactory) {
    StringBuilder sb = new StringBuilder();
    HashMap<String, User> users = dataFactory.users;
    ArrayList<Transaction> transactions = dataFactory.transactions;

    sb.append("USERS:\n");
    for (User user : users.values()) {
        sb.append("* ").append(user.getUserName()).append(" - ").append(user.getDisplayName()).append(" - ").append(user.getPassword()).append("\n");
    }

    sb.append("\nTRANSACTIONS:\n");
    for (Transaction transaction : transactions) {
        sb.append("* ").append(transaction.getDate()).append(" - ").append(transaction.getUserNameFrom()).append(" - ").append(transaction.getReason()).append("\n");
    }

    return sb.toString();
}
    
    //build data for table
    //builf users and their info

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginWindow;
    private javax.swing.JPanel MainWindow;
    private javax.swing.JPanel MainWindow_Panel_Dashboard;
    private javax.swing.JPanel MainWindow_Panel_Dues;
    private javax.swing.JPanel MainWindow_Panel_History;
    private javax.swing.JPanel MainWindow_Panel_Holder;
    private javax.swing.JToggleButton MainWindow_ToggleB_Dashboard;
    private javax.swing.JToggleButton MainWindow_ToggleB_Dues;
    private javax.swing.JToggleButton MainWindow_ToggleB_History;
    private javax.swing.JButton Main_Dashboard_Button_Owe;
    private javax.swing.JButton Main_Dashboard_Button_Request;
    private javax.swing.JScrollPane Main_Dashboard_Table_Data;
    private javax.swing.JScrollPane Main_Dashboard_Table_Data1;
    private javax.swing.JScrollPane Main_Dashboard_Table_Data2;
    private javax.swing.JLabel Main_Dashboard_Text_ExpectedProfits;
    private javax.swing.JLabel Main_Dashboard_Text_Money;
    private javax.swing.JButton Main_UserInfo_Button_LogOut;
    private javax.swing.JLabel Main_UserInfo_Text_Username;
    private javax.swing.JPanel RegistrationWindow;
    private javax.swing.JPanel UserInfo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton loginWindow_Button_newUser;
    private javax.swing.JButton loginWindow_button_enter;
    private javax.swing.JLabel loginWindow_label_password;
    private javax.swing.JLabel loginWindow_label_username;
    private javax.swing.JTextField loginWindow_textField_password;
    private javax.swing.JTextField loginWindow_textField_username;
    private javax.swing.JLabel longWindow_label_wornglogin;
    // End of variables declaration//GEN-END:variables
}
